version: 0.2

phases:
  install:
    commands:
      - echo Logging in to ECR...
      - AWS_AUTH=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $AWS_AUTH | docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URI .
      - echo Tagging the image for deployment...

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO_URI

