version: 0.2

phases:
  install:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_ REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URI:latest .
      - echo Tagging the image for deployment...
      - docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$CODEBUILD_BUILD_ID

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO_URI:$CODEBUILD_BUILD_ID

artifacts:
  paths:
    - buildspec.yml
